version: '2.1'
services:
  registry:
    image: eclipsebasyx/aas-registry:1.1.0
    container_name: registry
    volumes:
        - ./conf/reg-config:/usr/share/config:z
    ports:
      - 8082:4000

  aas:
    image: eclipsebasyx/aas-server:1.1.0
    container_name: aas
    volumes:
        - ./conf/aas-config:/usr/share/config:z
    ports:
      - 4001:4001
#   dashboard-aas:
#     image: eclipsebasyx/dashboard-aas:0.1.0-SNAPSHOT
#     container_name: dashboard-aas
#     environment:
#       - BaSyxDashboardSubmodel_Min=15
# #      - BaSyxDashboardSubmodel_Max=30
#     ports:
#       - 6400:6400
  # node-red:
  #   image: nodered/node-red
  #   container_name: node-red
  #   ports:
  #     - 1880:1880
  #   volumes:
  #     - ./node-red:/data
  grafana:
    image: grafana/grafana:7.4.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./lib:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
