version: '2.1'
services:
  registry:
    image: eclipsebasyx/aas-registry:1.0.3
    container_name: registry
    volumes:
        - ./conf/reg-config:/usr/share/config
    ports:
      - 8082:4000

  aas:
    image: eclipsebasyx/aas-server:1.0.1
    container_name: aas
    volumes:
        - ./conf/aas-config:/usr/share/config
    ports:
      - 4001:4001

